spring:
  application:
    name: api-hub
  datasource:
    url: jdbc:mysql://${APIHUB_MYSQL_HOST:localhost}:3306/${APIHUB_MYSQL_DB:apihub}?useSSL=false&serverTimezone=Asia/Shanghai
    username: ${APIHUB_MYSQL_USER:apihub}
    password: ${APIHUB_MYSQL_PASSWD:apihub-test}
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-wait: -1ms
          max-active: 16
  mail:
    host: smtp.qq.com
    port: 587
    username: ${APIHUB_QQ_MAIL_USERNAME}
    password: ${APIHUB_QQ_MAIL_PASSWD} # 授权码
  sms:
    accessKeyId: ${APIHUB_ALIYUN_SMS_ACCESS_KEY_ID}
    accessKeySecret: ${APIHUB_ALIYUN_SMS_ACCESS_KEY_SECRET}
    signName: ${APIHUB_ALIYUN_SMS_SIGN_NAME}
    templateCode: ${APIHUB_ALIYUN_SMS_TEMPLATE_CODE}

server:
  port: 9998
  servlet:
    context-path: /api/v2

# 监控项配置
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

# Sa-Token配置
sa-token: # token名称 (同时也是cookie名称)/
  token-name: Authorization
  # token有效期，单位秒，-1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期)，单位秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  is-read-head: true

# 文档增强
knife4j:
  enable: true

alipay:
  gatewayUrl: https://openapi.alipay.com/gateway.do
  appId: ${APIHUB_ALIPAY_APP_ID}
  alipayPublicKey: ${APIHUB_ALIPAY_PUBLIC_KEY}
  alipayPrivateKey: ${APIHUB_ALIPAY_PRIVATE_KEY}
  returnUrl:
  notifyUrl: ${APIHUB_ALIPAY_NOTIFY_URL}
  maxQueryTime: 600

storage:
  type: ${APIHUB_STORAGE_TYPE:local}
  sizeLimit: 5 # MB
  local:
    root: ${APIHUB_STORAGE_LOCAL_ROOT:data}
  aliyun:
    endpoint: ${APIHUB_ALIYUN_OSS_ENDPOINT} # oss对外服务的访问域名
    accessKeyId: ${APIHUB_ALIYUN_OSS_ACCESS_KEY_ID} # 访问身份验证中用到用户标识
    accessKeySecret: ${APIHUB_ALIYUN_OSS_ACCESS_KEY_SECRET} # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: ${APIHUB_ALIYUN_OSS_BUCKET_NAME:apihub} # oss的存储空间
  minio:
    endpoint: ${APIHUB_MINIO_ENDPOINT} #MinIO服务所在地址
    bucketName: apihub #存储桶名称
    accessKey: ${APIHUB_MINIO_ACCESS_KEY_ID} #访问的key
    secretKey: ${APIHUB_MINIO_ACCESS_KEY_SECRET} #访问的秘钥

ocr:
  baidu:
    appId: ${APIHUB_BAIDU_OCR_APP_ID}
    appSecret: ${APIHUB_BAIDU_OCR_APP_SECRET}
    apiAuth: https://aip.baidubce.com/oauth/2.0/token?grant_type=client_credentials
    urlPattern: "%s&client_id=%s&client_secret=%s"
    apiOcr: https://aip.baidubce.com/rest/2.0/ocr/v1/vat_invoice

browser:
  path: "/home/zoz/Downloads/chrome-linux/chrome"